# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
